services:
  - type: web
    name: plot-extract-web
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python WebExtract/app.py
    autoDeploy: true
